Evaluating random order FCFS with Chain type: Dollar; Model: MaxVaxHPIDistBLP; M = 5, K = 10000, R = None, Heuristic: False.
 Results stored at /export/storage_covidvaccine/Result/MaxVaxHPIDistBLP/M5_K10000_4q/Dollar

1701111237.1332715
Start constructing blocks...

1701111245.857527
Start assignments...

***************** EVALUATING WITH MNL ******************

Computed utils in: 51.401 seconds.
Assigning individuals...
time3 - time2: 0.627
Traceback (most recent call last):
  File "/mnt/phd/jihu/VaxDemandDistance/main.py", line 59, in <module>
    main(Model, Chain, K, M, nsplits, capcoef)
  File "/mnt/phd/jihu/VaxDemandDistance/main.py", line 46, in main
    evaluate_main(Model, Chain, M, K, nsplits, capcoef, R)
  File "/mnt/phd/jihu/VaxDemandDistance/utils/evaluate_main.py", line 27, in evaluate_main
    evaluate_chain_RandomFCFS(Model, Chain, M, K, nsplits, R, heuristic, constraint, path)
  File "/mnt/phd/jihu/VaxDemandDistance/utils/evaluate_main.py", line 53, in evaluate_chain_RandomFCFS
    run_assignment(Chain, M, K, R, heuristic, constraint, block, block_utils, distdf, path, Pharmacy=True)
  File "/mnt/phd/jihu/VaxDemandDistance/utils/evaluate_model.py", line 190, in run_assignment
    af.random_fcfs_mnl_eval(economy, distcoefs, abd, 5000)
  File "/mnt/phd/jihu/VaxDemandDistance/Demand/demand_utils/assignment_funcs.py", line 304, in random_fcfs_mnl_eval
    print(economy.utils[tt][ii], economy.utils[tt][ii][util_subset_bools], ii_choice)
UnboundLocalError: local variable 'ii_choice' referenced before assignment
